language: php

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

script:
  - git config core.whitespace tab-in-indent,trailing-space,space-before-tab,cr-at-eol &&
    git show --oneline --check &&
    bash -x ./php.sh &&
    echo $PATH &&
    which php &&
    ls /home/travis/.phpenv/bin &&
    wget https://raw.githubusercontent.com/michaelklishin/jdk_switcher/724202b21/jdk_switcher.sh &&
    chmod +x ./jdk_switcher.sh &&
    source ./jdk_switcher.sh &&
    jdk_switcher use oraclejdk8 &&
    wget https://raw.githubusercontent.com/paulp/sbt-extras/53493316/sbt && chmod +x ./sbt &&
    ./sbt test &&
    find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
